# Generated by Django 5.0.3 on 2024-04-18 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(blank=True, max_length=7)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fam', to='core.family')),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='family_tree', to='core.person'),
        ),
        migrations.AddField(
            model_name='family',
            name='father',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_father', to='core.person'),
        ),
    ]
